# Generated by Django 4.0.1 on 2022-01-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse_news', '0003_work_job_ask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name_plural': 'Shows'},
        ),
    ]
