# Generated by Django 4.0.1 on 2022-01-30 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_cat', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('by', models.CharField(default='', max_length=100, null=True)),
                ('descendants', models.CharField(default='', max_length=100, null=True)),
                ('score', models.CharField(default='', max_length=100, null=True)),
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('text', models.TextField(default='', null=True)),
                ('time', models.CharField(default='', max_length=100, null=True)),
                ('title', models.CharField(default='', max_length=100, null=True)),
                ('type', models.CharField(default='', max_length=100, null=True)),
                ('url', models.URLField(default='', null=True)),
                ('category_fk', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='parse_news.category')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
