# Generated by Django 4.0.1 on 2022-02-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_id_alter_productcategory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.CharField(default='', max_length=200),
        ),
    ]
